version: "3"
services:
  connector:
    container_name: mongo-connector
    restart: always
    volumes:
      - ./mongo-connector:/mongo-connector
    build:
      context: .
      args:
        SOURCE_HOST: "" # mognodb://192.168.0.1
        TARGET_HOST: "" # mongodb+srv://account:password@abcd.mongodb.net/shopline
